Step2の反映
NBemura/dept_design_fe_work01 pull request #2
Opened 2023-11-30 09:10 UTC by NBemura

# Step2
モックデータを全て反映したブックリスト及び、ヘッダーを作成する。

newbeescoltd/nb_study_react#17

2023-12-01 01:45 UTC, NBmaeda requested changes
Step2の実装ありがとうございます！
emuさんのコードはCSS設計が綺麗にされており、htmlを含め上手に構造化されているなと思います👏
今回は数点、Reactでの開発ならではの重要なポイントを含むFeedbackを行いました。
ご確認・ご対応のほどよろしくお願いします🙏

また、それに加えてコンポーネントの分割も視野に入れても良いかもしれません。
この後コード量が増えていくので、分割した方が可読性が高まると思います。
今回の修正でもStep3でも結構ですので、取り組んでみてください！

2023-12-01 01:45 UTC, NBmaeda commented on booklog/src/App.tsx
> +                    <img src={item.volumeInfo.imageLinks.thumbnail} alt={item.volumeInfo.title} />
この行をはじめ、`item.volumeInfo.[prop_name]`の記載がちょっと冗長なので、分割代入を利用してスッキリ書けるようにしてみてください💡

2023-12-01 01:45 UTC, NBmaeda commented on booklog/src/App.tsx
> +                  <div className="c-book-list__other">
もし`authors`も`publisher`もデータが存在しない場合、不要な`<div className="c-book-list__other">`のみ出力されてしまいます。
これを防ぐために、この行に関しても条件付きレンダリングを適用した方が好ましいです。

2023-12-01 01:45 UTC, NBmaeda commented on booklog/src/App.tsx
chromeのdeveloper toolでconsoleを確認すると、以下のようなエラーが出力されています。
`Warning: Each child in a list should have a unique "key" prop.`

[こちら](https://ja.react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key)の公式ドキュメントで同じ状況に関して言及されているので、参照してこのエラーを解消してみてください💡
あえて原因等は説明しないでおきますが、不明点等があればいつでもご質問ください！！

2023-12-12 04:35 UTC, NBmaeda requested changes
修正お疲れ様です👏
propsの型定義や型注釈等も含め、コンポーネントの分割は良くできていると思います！

その上で+αの改善点やコメントに関する情報等を記載しました。
後もう一歩というところなので、対応をよろしくお願いします！🙇

2023-12-12 04:35 UTC, NBmaeda commented on booklog/src/components/Booklist.tsx
> +// App.tsxのuseStateの箇所で使った型とは別に、子コンポーネントでも定義が必要？？
型ややこしいですよね🥹

それぞれの箇所で以下のような違いがあります。
- `Booklist.tsx`の6~8行目は、`Booklist`コンポーネントのpropsの型指定。
- 「App.tsxのuseStateの箇所で使った型」は、変数`items`の型指定。

どちらも`BookItem`を共通で読み込んで指定してはいますが、それぞれ別の変数・引数の型を指定する記述となるため両方必要です。

一方で`type BookItem`自体は上記のように複数の箇所で読み込む型となるため、共通化してexportしているため再定義は必要ありません。
`export type BookItem`とすることで、型のexportを行うことができます。`types/index.ts'を参照して見てください。

上記を踏まえた上で[このセクション](https://typescriptbook.jp/overview/static-type#%E5%9E%8B%E6%B3%A8%E9%87%88%E3%82%92%E3%82%B3%E3%82%B9%E3%83%88%E3%81%A8%E8%80%83%E3%81%88%E3%82%8B%E3%81%8B%E6%8A%95%E8%B3%87%E3%81%A8%E8%80%83%E3%81%88%E3%82%8B%E3%81%8B)を読むと、少し理解が深まるかもしれません。

2023-12-12 04:35 UTC, NBmaeda commented on booklog/src/components/Booklist.tsx
> +type BookItemsProps = {
これは好みですが、コンポーネント`Booklist`のpropsのための方であれば名称は`BooklistProps`にすると分かりやすいと思います。

たとえばさまざまな型定義をexportした場合を考えると、VSCodeなどのエディタで補完を行う際に型の名前が大量に出てきます。
その場合に「コンポーネント名 + Props」といった形で命名規則を統一しておくと、どの型を選択すればいいかが一見して分かるため非常に便利です。

この命名規則は「[MUI](https://mui.com/)(Material UI)」でも採用されている規則のため、一般的に広く使われています。

2023-12-12 04:35 UTC, NBmaeda commented on booklog/src/components/Booklist.tsx
> +      {/* 複数の式が入る場合は”()”ではなく”{}” */}
ちょっとこのコメントが気になったので、関連しそうな記事を共有しておきます💡
- [React コンポーネントでJSXが複数行になる場合になぜ()で囲むのか？](https://qiita.com/saba_can00/items/1d31b06b2c62feac1027)
- [JSX に波括弧で JavaScript を含める](https://ja.react.dev/learn/javascript-in-jsx-with-curly-braces)
- [React コンポーネントのブロック{} か()で何が違うのか](https://zenn.dev/hulk510/articles/e03ac1b6a7dd8e1692bb)

以下を区別できるようになると、ここのコメントの内容が体系立てて理解できるかもしれません🤔
- グループ化演算子の`()`
- 関数ブロックの`{}`
- JSX内で変数等を展開するための`{}`

2023-12-12 04:35 UTC, NBmaeda commented on booklog/src/components/Booklist.tsx
> +        const { imageLinks, title, description, authors, publisher, previewLink } = item.volumeInfo
良いですね、きちんと分割代入を使用できています👏
propsの量が少ない場合は、15行目の`map()`メソッドに渡す関数の引数の段階で分割代入を使用する形でも良いので、使い分けてみてください。

2023-12-12 04:35 UTC, NBmaeda commented on booklog/src/styles/header.css
ディレクトリ構造に関して1つアイデアを共有します。
コンポーネント化のメリットの1つに、HTML構造とスタイルの定義を1つのコンポーネントに閉じ込めることで、保守性が向上するというものがあります。

`components/`ディレクトリ以下にtsx(JSX)のファイル、`styles/`ディレクトリ以下にCSSのファイルを管理する現在の管理方法だと、HTML構造の定義とスタイルの定義の管理場所がばらけてしまいます。

旧来のフロントエンド開発であれば、HTMLとCSSとのファイルをまとめる方法が主流であったため上記の方法が一般的でしたが、UIのコンポーネント化という文脈で考えると`components/`ディレクトリ以下にtsx(JSX)ファイルとCSSファイルをまとめて管理する方が効果的な場合が多く、一般的に使用されています💡

そのため今回は、`components/`ディレクトリ以下に両方のファイルをまとめる形に変更してみてください。
その上で、この後のStepでコンポーネントが増えた際にどのようにディレクトリ構造を作っていくかを考えて見てください。

2023-12-14 10:03 UTC, NBemura commented on booklog/src/components/Booklist.tsx
> +// App.tsxのuseStateの箇所で使った型とは別に、子コンポーネントでも定義が必要？？
なるほどです！
変数とPropsでそれぞれ必要ということですね😀
Booklist.tsxで最初、型指定をせずエラーがたくさん出てきたのでビビりました😅

2023-12-14 10:04 UTC, NBemura commented on booklog/src/components/Booklist.tsx
> +type BookItemsProps = {
命名規則についても解説をありがとうございます！

2023-12-14 10:12 UTC, NBemura commented on booklog/src/components/Booklist.tsx
> +      {/* 複数の式が入る場合は”()”ではなく”{}” */}
{}はオブジェクトで使う、文字列ではなくJSが使える、
くらいの認識しかなかったため、共有いただいた記事がとても参考になりました！

2023-12-14 10:15 UTC, NBemura commented on booklog/src/styles/header.css
昔の記憶でディレクトリ構造をわけていたのですが、今はそのようになっていたのですね🤩
たしかにコンポーネントごとに格納しておいた方がファイルアクセスもよく、わかりやすいです！

2023-12-15 02:28 UTC, NBmaeda approved these changes
修正お疲れ様です！とても良くなったと思います👏
Step2の完了、おめでとうございます🎉

今回は慣習的な内容にも触れました。
この部分を体系的にまとめている資料はあまりないのですが、勉強や調べ物をしていく中での一般的な記述方法やベストプラクティスを徐々に吸収していくと良いと思います💡

最後に1つだけ言い忘れていたことを伝えておきます。
CSSファイルの名前ですが、コンポーネントとの対応関係がわかりやすいように`Booklist.css`のように最初を大文字にするとより良いと思います。
Step3での対応で良いので、ぜひ修正してみてください。

2023-12-19 09:21 UTC, merged