Step4 読書タイマーの追加
NBemura/dept_design_fe_work01 pull request #4
Opened 2024-01-22 08:00 UTC by NBemura

useEffectを使って読書時間タイマーを実装

https://github.com/newbeescoltd/nb_study_react/issues/19

2024-01-23 04:54 UTC, NBmaeda reviewed
ロジックですが、良い方向性だと思います🎉
その上でより良くするためのヒント的なものを書かせてもらいました。
今の方向性でブラッシュアップしていただければと思います💪

関数の分け方や命名など基本的な部分が分かりやすいため、コード全体として読みやすかったです👏さすえむです👏

2024-01-23 04:54 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +  const [selectedTime, setSelectedTime] = useState(5)
この箇所なのですが、個人的にはStep3で学んだ「非制御コンポーネント」を使用しても良いと思っています💡
というのも`select`要素を変更しただけではコンポーネント側で再レンダリングする必要はないですし、useRefを使って状態の保持をDOMに任せてしまうことでReact側で保持する状態が少なくて済むためです。

useStateを使用して制御コンポーネントとする今の状態でも問題はないのですが、上記のような選択肢とその理由があることを参考にしてみてください。

2024-01-23 04:54 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +  console.count('レンダリングです')
レンダリングの発生タイミングを気にしているのはとても良いですね👏

2024-01-23 04:54 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +    if (timerRunning) {
タイマーの動作状態をフラグ管理して処理を分けているのは良いですね👏

>[!tip]
>`if`ブロックを使用した場合、それだけでネストが深くなってしまいコードの可読性が低下してしまいます。
> 以下のようにすることで、同様の効果を得つつもネストを減らすことができます。

```
if (timerRunning) {
    // 何らかの処理
}
```
↓
```
if (!timerRunning) return;
// 何らかの処理
```

2024-01-23 10:03 UTC, NBemura commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +  const [selectedTime, setSelectedTime] = useState(5)
Step3で変更のたびにレンダリングが必要のないものはuseRefを使う、と学んだことをすっかりすっぽかしてしまいました😇
useRefで修正をしてみました🙇

2024-01-23 10:05 UTC, NBemura commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +    if (timerRunning) {
この書き方は初めて知りました！
確かにネストの深さはコードが読みにくくなってしまいますね🤔
修正してみました🙇

2024-01-24 03:39 UTC, NBmaeda requested changes
ブラッシュアップお疲れ様です！👏
良くまとまっており、良いコードだと思います🎉

ただ1点、タイマー終了時の挙動として実装してほしい箇所があったのでコメントさせてもらいました。
あと一歩だと思うのでよろしくお願いします！💪

2024-01-24 03:39 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +    //（parseIntからNumberにするとエラーが消えたのですが、使い分けがよくわかっていません…）
ここですが、VSCodeを使っているのであれば関数名にマウスオーバーすることでヒントが得られます。
以下は僕の環境でマウスオーバーした時に表れるポップアップをキャプチャしたものです。

- `Number()`
<img width="495" alt="スクリーンショット 2024-01-24 12 09 43" src="https://github.com/NBemura/dept_design_fe_work01/assets/119549407/b30482c5-88dd-4621-bce1-602d569a2398">

- `parseInt()`
<img width="492" alt="スクリーンショット 2024-01-24 12 10 04" src="https://github.com/NBemura/dept_design_fe_work01/assets/119549407/9e455b4f-7ca1-4eb5-a4eb-ee555e205124">

第一引数を見ると`Number()`の方は`value?: any`、`parseInt()`の方は`string: string`となっているかと思います。
引数としている変数には[optional chaining](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining)を使用していますが、optional chainingは以下のような仕様になっています。
> 参照が [nullish](https://developer.mozilla.org/ja/docs/Glossary/Nullish) ([null](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/null) または [undefined](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/undefined)) の場合にエラーとなるのではなく、式が短絡され undefined が返される...

そのため`selectedTimeRef.current?.value`の型は`string | undefined`となり、`parseInt()`の引数としては適さないためエラーが発生します💡

このようにVSCodeを活用することでエラーの原因や関数等の仕様を調べることができるため、是非活用してみてください！
初めは全然わからないとは思いますが、徐々に使い方や勘所がわかってくると思います！(僕もそうでした😅)

2024-01-24 03:39 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
>    useEffect(() => {
useEffectの中身、すごく良いですね👏
前回書きそびれましたが、クリーンアップ関数もうまく利用できており良いと思います。
クリーンアップ関数の有無でパフォーマンスに影響が出るため、useEffectの使用の際は意識してみてください💡

2024-01-24 03:39 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
>        <div className="c-reading-timer__counter">{formatTime(currentTime)}</div>
細かいところではあるのですが、目標物ではタイマー終了時に「読書タイマー 終了」と表示が変わると思います。
こちらの実装をお願いします🙏

2024-01-24 03:39 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +  const selectedTimeRef = useRef<HTMLSelectElement>(null)
うまくuseRefを利用できていると思います👏
最初は難しいと思いますが、制御/非制御を使い分けるという選択肢を持っておくと一段上の実装ができると思います！

2024-01-25 08:05 UTC, NBemura commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +    //（parseIntからNumberにするとエラーが消えたのですが、使い分けがよくわかっていません…）
詳細解説をありがとうございます！
オプショナルチェーンを使用していることで`undefined`が返される可能性があり、`parseInt()`はstringしか対応できないため型エラーがでるということでしょうか🙃
VSCodeの使用方法まで感謝です😭

2024-01-25 08:08 UTC, NBemura commented on booklog/src/components/Readingtimer/Readingtimer.tsx
>        <div className="c-reading-timer__counter">{formatTime(currentTime)}</div>
再buildしていなかったため古いpreviewを見ておりました😇
あまりスマートな実装でないかもしれませんが、修正してみました🙇

2024-01-25 08:52 UTC, NBmaeda approved these changes
修正ありがとうございます！
問題なかったのでApproveしました、お疲れ様です🎉

useEffectの使い方は多少理解できたのではないかと思います。
[公式ドキュメント](https://ja.react.dev/learn/you-might-not-need-an-effect)でも最終手段として提案されてはいるのですが、手段として理解できるようにしておいてください💡
いよいよ折り返しです、引き続き頑張っていきましょう！

2024-01-25 08:56 UTC, NBmaeda commented on booklog/src/components/Readingtimer/Readingtimer.tsx
> +    //（parseIntからNumberにするとエラーが消えたのですが、使い分けがよくわかっていません…）
@NBemura 
> オプショナルチェーンを使用していることでundefinedが返される可能性があり、parseInt()はstringしか対応できないため型エラーがでるということでしょうか🙃

ご認識の通りです！👏
VSCodeは結構痒い所に手が届くエディタなので、プラグインの利用も含め活用していくと良いと思います💡

2024-01-26 07:39 UTC, merged