Step5 APIの連携を行い、検索結果をブックリストに反映
NBemura/dept_design_fe_work01 pull request #5
Opened 2024-02-06 08:21 UTC by NBemura

https://github.com/newbeescoltd/nb_study_react/issues/20

2024-02-06 12:12 UTC, NBmaeda requested changes
Step5の実装お疲れ様です👏
いよいよ本格的にロジックを扱う段階になってきて、なかなか大変だったと思います🤯

ひとまずアプリの機能としてはちゃんと検索ができるようです、素晴らしい🎉
その上で、コードをよりブラッシュアップするためのヒントを記載しました。

なかなかの分量になってしまったのですが、一つ一つじっくり取り組んでいただけるとレベルアップできると思います！
質問があればいつでも待っています、引き続きよろしくお願いします💪

2024-02-06 12:12 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const [displayNum, setDisplayNum] = useState<number>(10)
`displayNum`に関してはuseStateで管理しなくても大丈夫です💡
stateとして管理したい値の特徴として、「操作をする中で変更される値」かつ「コンポーネントの再レンダリング間で引き継ぎをしたい値」という点が挙げられます。

例えば`totalItems`は「検索によって変化する値」であり、「次の検索時まで引き継ぎをしたい値」となるため`useState`でstate管理をしたい値となります。
しかし`displayNum`は今回の場合は「動作の中で変わらない値」であるため、再レンダリング間で特に引き継ぎをしなくても良い値です。(再レンダリング毎に固定の値を参照すれば良いため)

現在`Search.tsx`の`getBooks`関数の中で`displayNum`を宣言しているものを、例えば関数コンポーネント`App`の外(`App.tsx`の8行目など)で以下のような形で宣言するとアプリケーション全体で参照できる[定数](https://e-words.jp/w/%E5%AE%9A%E6%95%B0.html)とすることができます。
※定数は慣例として[アッパースネークケース](https://e-words.jp/w/%E3%82%B9%E3%83%8D%E3%83%BC%E3%82%AF%E3%82%B1%E3%83%BC%E3%82%B9.html#Section_%E3%82%A2%E3%83%83%E3%83%91%E3%83%BC%E3%82%B9%E3%83%8D%E3%83%BC%E3%82%AF%E3%82%B1%E3%83%BC%E3%82%B9/%E3%82%B3%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%88%E3%82%B1%E3%83%BC%E3%82%B9)で記載することが多いです。

```
...
import './App.css'

const DISPLAY_NUM = 10; // アッパースネークケースで記載します

function App(){
...
```

その上で`Search`コンポーネントのpropsとして`displayNum`を渡す実装にすると、`Search`コンポーネントの汎用性も向上して良いかなと思います。

2024-02-06 12:12 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const handleSearchItemsUpdate = (newSearchItems: BookItem[], newTotalItems: number, newDisplayNum: number) => {
細かいのですが、ここの関数名はちょっと注意した方が良いかもしれません🚨

一般的に関数名は、その関数が行う処理に着目して命名するのはご存知だと思います。
そういう意味で`searchItemsUpdate`であれば問題ないと思います👍

ただ`handle`と付いてしまうと、「あるイベントをハンドルする[イベントハンドラ](https://developer.mozilla.org/ja/docs/Learn/JavaScript/Building_blocks/Events)(発生したイベントに応答して動作するコード)」と一般的に認識されます。
そのため`handle`をつけるのであれば、Searchをハンドルするという意味合いで`handleSearch`のようにすると分かりやすいと思います。

命名規則は慣習や経験値が関わってくる為に諸説あるのですが、他の人のコードを読んで徐々に知識を蓄えていただければと思います💪

2024-02-06 12:12 UTC, NBmaeda commented on booklog/src/components/Search/Search.tsx
> +      console.error('ネットワークエラーです。', error)
エラーメッセージに関する注意です🚨

エラーのステータスのうちネットワークに関するもの以外も存在するため、このエラーメッセージはあまり好ましくないです😫
一般的なエラーのステータスには[このように](https://developer.mozilla.org/ja/docs/Web/HTTP/Status)非常に多くのステータスが存在します。
Google Book APIのステータスコード一覧は見つからなかったのですが、[このように](https://stackoverflow.com/questions/69935318/google-book-api-error-429-client-error-too-many-requests-for-url)リクエスト数(検索試行回数)が多すぎるためにエラーが返される場合もあります。

[Fetch API](https://developer.mozilla.org/ja/docs/Web/API/Fetch_API)の[Response](https://developer.mozilla.org/ja/docs/Web/API/Response)オブジェクトの`ok`プロパティは[MDNのページ](https://developer.mozilla.org/ja/docs/Web/API/Response/ok)を見ると以下のように書かれています。
>ok は [Response](https://developer.mozilla.org/ja/docs/Web/API/Response) インターフェイスの読み取り専用プロパティで、このレスポンスが（ステータスが 200-299 で）成功したかどうかを表す論理値です。

そのため今回の処理ではネットワークに関するエラー以外の場合でも200-299以外のエラーは一律で`throw new Error`されてしまうため、「ネットワークエラーです。」とメッセージを表示するのはエラー解消の妨げになってしまう場合があります。
この場合は素直に`console.error(error)`とするだけでも大丈夫だと思います。

Fetch APIのエラー処理に関しては[この記事](https://zenn.dev/junki555/articles/4ab67fc78ce64c)がわかりやすいため、ぜひ見てみてください💡
エラー処理はちょっとややこしいと思いますが、適切なエラーは問題解決の助けになる便利なものです。ゆっくりとでもいいのでしっかり学んでいきましょう💪

2024-02-06 12:12 UTC, NBmaeda commented on booklog/src/components/Search/Search.tsx
> +      const data = await response.json()
ここ詰まりポイントですよね🥹

まずはどういう型のデータが返ってくるか見てみましょう。
そのために36行目に以下のコードを挿入します。
```
console.log('data: ', data)
```

そして検索をすると、コンソールに以下のように出力されると思います。
※数値等は検索ワードによって異なります。
```
data: {kind: 'books#volumes', totalItems: 702, items: Array(10)}
```

これを元に型を定義してあげると、以下のようになると思います。
```
type Result = {
  kind: string
  items: BookItem[]
  totalItems: number
}
```

これを利用して以下のように型アサーションを行うだけでここは一旦OKです。
```
const data = await response.json() as Result
```

ここを突き詰めると課題として難しくなりすぎる気はするので今回は省略して上記のようにしていますが、APIから取得したデータの型安全性をどう担保するかという方法論があることは知っておいてほしいです。
解決のためには以下のような方法や、ライブラリの利用([zod](https://qiita.com/YudaiTsukamoto/items/37ee62d3a7ff6e2d52f9)など)などがあるため、知っておくと良いと思います。
https://zenn.dev/uzimaru0000/articles/json-type-validation

2024-02-06 12:12 UTC, NBmaeda commented on booklog/src/components/Search/Search.tsx
> +  }, [query])
ここなんですが「`query`をstateに保持する」ことと、「`getBooks`をuseEffectを使って実行させる」ことを見直してみましょう🤔

## `query`をstateに保持する
`query`としてセットされる値は、`searchRef`で指定している`input`要素が保持してくれています。
`query`はAPIにリクエストを送信する際にのみ使用されるので、わざわざstateとして保持しなくても、リクエストの際に都度`searchRef.current`を参照するでも良いのではないでしょうか💡

## `getBooks`をuseEffectを使って実行させる
このEffectが実行されるのは`query`が更新されるとき、つまり`handleSearchSubmit`が実行されるタイミングです。
`getBooks`の中身はAPIにリクエストを送信して`handleSearchItemsUpdate`を実行する処理ですが、useEffectを使用するのではなくもっとシンプルなトリガーで実行させることはできないでしょうか🤔

useEffectを使ってみよう！というStepを設けておいて何だよという感じかもしれませんが、useEffectは積極的に使うものではないんです🤯
[公式ドキュメント](https://ja.react.dev/learn/you-might-not-need-an-effect)にもありますが、できるだけそれ以外の方法を使用した上での**非難ハッチ**として使用することを意識してみてください。

2024-02-08 10:13 UTC, NBemura commented on booklog/src/App.tsx
> +  const [displayNum, setDisplayNum] = useState<number>(10)
なんでもstateに入れなきゃ病になっておりました😅
とてもわかりやすい解説もありがとうございます！定数の記載方法についてのTipsもありがたいです🙏

2024-02-08 10:13 UTC, NBemura commented on booklog/src/App.tsx
> +  const handleSearchItemsUpdate = (newSearchItems: BookItem[], newTotalItems: number, newDisplayNum: number) => {
関数を作る時なんでもかんでもhandleとつけてしまっていました😭
searchItemsUpdateで行きたいと思います💪

2024-02-08 10:14 UTC, NBemura commented on booklog/src/components/Search/Search.tsx
> +      console.error('ネットワークエラーです。', error)
記事の紹介をありがとうございます！
エラー内容が今後どう役立っていくのか、まだ実感が湧かない部分もありますが、表示すべきエラー内容がわかりました。修正してみましたのでご確認をお願いいたします🙇

2024-02-08 10:14 UTC, NBemura commented on booklog/src/components/Search/Search.tsx
> +      const data = await response.json()
どうしても赤線が消えなくて途方に暮れていました🙃
対策方法をありがとうございます！型アサーション、そういえばありました！復習しておきます🙇

2024-02-08 10:15 UTC, NBemura commented on booklog/src/components/Search/Search.tsx
> +  }, [query])
APIを呼ぶときにuseEffectを使う事例を参考にしていたので、「API！ならばuseEffectだ！」となんか不安で使ってしまっておりました🤯

2024-02-08 11:01 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const handleSearchItemsUpdate = (newSearchItems: BookItem[], newTotalItems: number, newDisplayNum: number) => {
リーダブルコードという、エンジニアの間で定番になっている書籍があります💡
これは第三者でもわかりやすいコードを書くために、というようなコンセプトの書籍なのですが関数の命名に関しても言及があります。

以下の記事に要点がまとまっているので、この記事だけでもお時間ある時に是非目を通してみてください🙏
https://qiita.com/KNR109/items/3b14e2e8f89a33c0f959

2024-02-08 12:23 UTC, NBmaeda requested changes
ご対応ありがとうございます👏
方針も見えてきて、だいぶスッキリしたコードになってきたと思います🎉

ただ1点気をつけて欲しいことを記載しました。
今回の課題やこれくらい小さなアプリケーションだと特に問題はないのですが、今後のために考えて欲しい内容となっています。
各コンポーネントが疎結合である(互いに依存度が高くない)状態というのを意識すると、分かりやすいかもしれません💡

Step5もあと一息です。引き続き頑張っていきましょう！💪

2024-02-08 12:23 UTC, NBmaeda commented on booklog/src/components/Search/Search.tsx
> +  searchItemsUpdate: (newSearchItems: BookItem[], newTotalItems: number) => void
ここのプロパティに関して順番に見ていきます。

まず7行目は`DISPLAY_NUM`ではなく、`displayNum`とかの方が良いです💡
`App.tsx`で`DISPLAY_NUM`を定数として定義しているのですが、ここで定義するのはあくまで`Search`コンポーネントのプロパティであり、定数では無いです🤔
なのでここでは`displayNum: nubmer`としておいて、`Search`コンポーネントを呼び出す際に、`displayNum={DISPLAY_NUM}`というように定数`DISPLAY_NUM`を渡すのが一般的かなと思います。

8行目に関しても同じくです。
`App.tsx`において受け取っている関数`searchItemsUpdate`はこのコンポーネントから見ると、フォームがsubmit(search)あるいはgetBookが実行されたタイミングで実行される関数でしか無いわけです。
その為、意味的にもコンポーネントの汎用性的にもプロパティ名は`searchItemsUpdate`より好ましいものがあると思います。
例えば`onSubmit`のように`form`自体のイベントに着目するパターン、あるいは`onSearch`や`onFetchBooks(onGetBooks)`などコンポーネントの機能自体に着目するパターン等が考えられます。

上記のようにすることで、以下のような場合でもこのコンポーネントへの修正をすることなく、呼び出し側からも違和感のないわかりやすいコードを保つことができます。
- 表示件数に定数ではなく、ユーザーがセレクトボックスで選んだ値を適用する場合。
- 検索時に実行される関数として渡すのが`searchItemsUpdate`ではなく、`changeResults`の場合。

2024-02-09 03:11 UTC, NBemura commented on booklog/src/components/Search/Search.tsx
> +  searchItemsUpdate: (newSearchItems: BookItem[], newTotalItems: number) => void
詳細な解説をありがとうございます！
命名規則についても考えることがたくさんありますね😵‍💫
修正してみましたのでご確認をお願いいたします🙏
一点質問なのですが、`onFetchBooks={onGetBooks}`のように名前を変えてPropsを渡すことはよくある事でしょうか？

2024-02-09 04:44 UTC, NBmaeda requested changes
対応ありがとうございました！
ほぼほぼ問題ないのですが、意図がうまく伝わっていなかった箇所が修正必要かなと思いRequest changesとさせていただきました🙇

不明点や疑問等あればslackでも良いのでお気軽に投げてください🙏
引き続きよろしくお願いします！

2024-02-09 04:44 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const onGetBooks = (newSearchItems: BookItem[], newTotalItems: number) => {
すみません、ちゃんと意図が伝わっていなかったです🙇
ここの関数名は`searchItemsUpdate`で問題ないです。
今回のケースで言うと、`<Search onFetchBooks={searchItemsUpdate} ...`となるイメージです。

意味合いとしては、以下のような感じになるのですが伝わりますでしょうか？🤔
- `Search`コンポーネントはpropsとして渡される関数の命名や処理自体には関心を持たず、ただ`fetchBooks`が行われた時に実行する関数を渡すための、`onFetchBooks`というインターフェースを提供する。
- 呼び出し側は`Search`コンポーネントの処理に関してではなく、`App.tsx`においてどう言った処理を行うかに着目して命名した関数を、`fetchBooks`をトリガーとして実行するためにインターフェースに渡す。

2024-02-09 04:53 UTC, NBmaeda commented on booklog/src/components/Search/Search.tsx
> +  searchItemsUpdate: (newSearchItems: BookItem[], newTotalItems: number) => void
上記の質問は以下に記載したコメント内容と関わってくると思いますので、補足的な内容だけ返信します🙇
以下のコメントと合わせてご確認いただければと思います。


> 一点質問なのですが、onFetchBooks={onGetBooks}のように名前を変えてPropsを渡すことはよくある事でしょうか？

こういったケースもなくはないと思いますが、基本的には以下のような感じになると思います。
- `onClick={handleClick}`のように、DOMが提供するイベント(Clickイベント)に着目して命名した関数`handleClick`を渡す。
- `onFetchBooks={parseBooksData}`のように`fetchBooks`を行う際に実行して欲しい関数として、その関数が実行する内容のみに着目して命名した関数`parseBooksData`を渡す。

2024-02-09 05:43 UTC, NBemura commented on booklog/src/App.tsx
> +  const onGetBooks = (newSearchItems: BookItem[], newTotalItems: number) => {
すみません、`onFetchBooks(onGetBooks)`を`onFetchBooks={searchItemsUpdate}`と空目していたので、
いただいた内容で少し理解できたと思います🙇
それぞれのファイルで行っている役割で名前をつけるといった感じでしょうか🤔

`Search.tsx`の`onFetchBooks`…fetchした情報を渡すためのもの
`App.tsx`の`searchItemsUpdate`…検索した情報を更新する

2024-02-09 07:51 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const onGetBooks = (newSearchItems: BookItem[], newTotalItems: number) => {
ちょっと丸括弧の使い方が悪かったですね...すみません🙇
`onFetchBooks(onGetBooks)`は`onFetchBooks`あるいは`onGetBooks`という表現でした。

> それぞれのファイルで行っている役割で名前をつけるといった感じでしょうか🤔

これはご認識の通りです👏
> `App.tsx`の`searchItemsUpdate`…検索した情報を更新する

上記はその通りなのですが、 `onFetchBooks`に関しては僕は以下のように捉えています。伝わりますでしょうか？🤔

`Search.tsx`の`onGetBooks`…`getBooks`を実行したタイミングで、同時に実行する関数を受け取るためのプロパティ。
※`fetchBooks`ではなく`getBooks`の実行時に実行されるので、`onGetBooks`としています。

2024-02-09 07:59 UTC, NBmaeda approved these changes
度重なるご対応ありがとうございます！
問題ないと思います、Step5お疲れ様でした🎉

前回のコメントのツリーにもコメントを追加しておりますので、改めて確認いただけますと幸いです。
※`onfetchBooks`→`onGetBooks`の修正を行うのであれば、任意のタイミングで実施いただければと思います🙇

本Stepはこちらの説明がわかりにくかった点もあり申し訳なかったです🙇
以降のStep実施のタイミングでも結構ですので、わからないことが出てきたタイミングでいつでもお気軽にご質問いただければと思います🙏
Step6は比較的軽いものかなと思います。コンポーネントの分割等を意識しながら進めてみてください！

2024-02-09 08:14 UTC, merged